# WEION.SOCIAL NETLIFY CONFIG

[[headers]]
# Setup HTTP Security Headers.
	for = "/*"
	[headers.values]
		X-Frame-Options = "sameorigin"
		X-XSS-Protection = "1; mode=block"
		X-Content-Type-Options = "nosniff"
		X-Permitted-Cross-Domain-Policies = "none"
		Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
		Content-Security-Policy = "frame-ancestors 'self'; block-all-mixed-content; default-src 'self'; script-src 'self' d33wubrfki0l68.cloudfront.net 'report-sample' https://cdn.jsdelivr.net https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js https://d33wubrfki0l68.cloudfront.net/js/d9458e4a1b332a1e27e8b9f2a9c0008dfcf771bf/assets/js/index.js; style-src 'self' d33wubrfki0l68.cloudfront.net 'report-sample' https://cdn.jsdelivr.net https://d33wubrfki0l68.cloudfront.net https://fonts.googleapis.com; object-src https://wakatime.com; base-uri 'self'; form-action 'self'; connect-src 'self' cdn.jsdelivr.net fonts.googleapis.com fonts.gstatic.com; font-src 'self' https://cdn.jsdelivr.net https://fonts.gstatic.com; frame-src 'self' wakatime.com; img-src 'self' *.netlify.com badges.netlify.app cdn.jsdelivr.net d33wubrfki0l68.cloudfront.net fonts.gstatic.com; manifest-src 'self'; media-src 'self' d33wubrfki0l68.cloudfront.net; report-uri https://63f14d1d4bc18fcbbe21dd30.endpoint.csper.io/?v=0; worker-src 'self';"
		Referrer-Policy = "no-referrer-when-downgrade"
		Feature-Policy = "camera 'none'; fullscreen 'self'; geolocation *; microphone 'none';"

# Redirect Netlify.app to weion.social domain.
[[redirects]]
	from = "https://weion.netlify.app"
	to = "https://weion.social"
	status = 301
	force = true