# WEION.SOCIAL NETLIFY CONFIG

# Redirect Netlify.app to weion.social domain.
[[redirects]]
  from = "https://futureproof-portfolio-terry.netlify.app"
  to = "https://weion.social"
  status = 301
  force = true
