# WEION.SOCIAL NETLIFY CONFIG

[[headers]]
# Setup HTTP Security Headers.
	for = "/*"
	[headers.values]
		X-Frame-Options = "sameorigin"
		X-XSS-Protection = "1; mode=block"
		X-Content-Type-Options = "nosniff"
		X-Permitted-Cross-Domain-Policies = "none"
		Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
		Content-Security-Policy = "default-src 'self'; script-src 'report-sample' 'self' https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js; style-src 'report-sample' 'self' https://cdn.jsdelivr.net https://fonts.googleapis.com; object-src https://wakatime.com/share/@d381b7b5-d7c4-4c76-8fad-d29a8c2f7394/309c9908-c7fc-47e9-ae3e-5bf89550f884.svg; base-uri 'self'; connect-src 'self'; font-src 'self' https://cdn.jsdelivr.net https://fonts.gstatic.com; frame-src 'self'; img-src 'self' https://api.netlify.com https://badges.netlify.com https://ghchart.rshah.org; manifest-src 'self'; media-src 'self'; report-uri https://62c05e1b5a9e55900da78bac.endpoint.csper.io/?v=0; worker-src 'none';"
		Referrer-Policy = "no-referrer-when-downgrade"
		Feature-Policy = "camera 'none'; fullscreen 'self'; geolocation *; microphone 'none'; https://futureproof-portfolio-terry.netlify.app/*"
[[redirects]]
# Redirect Netlify.app to weion.social domain.
	from = "https://futureproof-portfolio-terry.netlify.app"
	to = "https://weion.social"
	status = 301
	force = true
