# WEION.DEV NETLIFY CONFIG

[[headers]]
# Setup HTTP Security Headers.
	for = "/*"
	[headers.values]
		X-Frame-Options = "sameorigin"
		X-XSS-Protection = "1; mode=block"
		X-Content-Type-Options = "nosniff"
		X-Permitted-Cross-Domain-Policies = "none"
		Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
		Content-Security-Policy = "default-src 'self'; frame-ancestors 'self'; script-src 'self' d33wubrfki0l68.cloudfront.net 'report-sample' https://cdn.jsdelivr.net; style-src 'self' d33wubrfki0l68.cloudfront.net 'report-sample' cdn.jsdelivr.net fonts.googleapis.com; object-src 'self' wakatime.com; frame-src 'self' wakatime.com; img-src 'self' wakatime.com *.netlify.com badges.netlify.app cdn.jsdelivr.net d33wubrfki0l68.cloudfront.net fonts.gstatic.com; font-src 'self' cdn.jsdelivr.net fonts.googleapis.com fonts.gstatic.com; base-uri 'self'; form-action 'self'; connect-src 'self' cdn.jsdelivr.net fonts.googleapis.com fonts.gstatic.com; media-src 'self' d33wubrfki0l68.cloudfront.net;"
		Feature-Policy = "camera 'none'; fullscreen 'self'; geolocation *; microphone 'none';"

# Redirect Netlify.app to weion.dev domain.
[[redirects]]
	from = "https://weion.netlify.app"
	to = "https://weion.dev"
	status = 301
	force = true
